HTML/lesson 28 upgrade to data-base/UPGRADE/config/routes.rb
Rails.application.routes.draw do
    resources :user_forms
    root to: "home#index"

    get 'contacts/index'
    get 'facts/index'

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
  

HTML/lesson 28 upgrade to data-base/UPGRADE/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

HTML/lesson 28 upgrade to data-base/UPGRADE/app/models/user_form.rb
class UserForm < ApplicationRecord

end

HTML/lesson 28 upgrade to data-base/UPGRADE/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
end

HTML/lesson 28 upgrade to data-base/UPGRADE/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

HTML/lesson 28 upgrade to data-base/UPGRADE/app/controllers/facts_controller.rb
class FactsController < ApplicationController
  def index
  end
end

HTML/lesson 28 upgrade to data-base/UPGRADE/app/controllers/forms_controller.rb
class FormsController < ApplicationController
  def form
  end
end

HTML/lesson 28 upgrade to data-base/UPGRADE/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

HTML/lesson 28 upgrade to data-base/UPGRADE/app/controllers/user_forms_controller.rb
class UserFormsController < ApplicationController
	# before_action :set_cart, only: [:show, :edit, :update, :destroy]

	def new
		@userform = UserForm.new	
	end
	
	def index
		@userforms = UserForm.all.order("created_at DESC")
	end

	def create
		@userform = UserForm.new(forms_params)
		@userform.save
		redirect_to user_forms_path
	end

	def show
		@userform = UserForm.find(params[:id])
	end

	def destroy 
		@userform = UserForm.find(params[:id])
		@userform.destroy 
		redirect_to user_forms_path
	end

	private

	def forms_params
		params.require(:form).permit(:name, :surname, :date, :country, :html, :javascript, :php, :css, :email, :password, :notification, :review)
	end
end

HTML/lesson 28 upgrade to data-base/UPGRADE/app/helpers/application_helper.rb
module ApplicationHelper
end

HTML/lesson 28 upgrade to data-base/UPGRADE/app/helpers/cont_helper.rb
module ContHelper
end

HTML/lesson 28 upgrade to data-base/UPGRADE/app/helpers/fact_helper.rb
module FactHelper
end

HTML/lesson 28 upgrade to data-base/UPGRADE/app/helpers/forms_helper.rb
module FormsHelper
end

HTML/lesson 28 upgrade to data-base/UPGRADE/app/helpers/home_helper.rb
module HomeHelper
end

HTML/lesson 28 upgrade to data-base/UPGRADE/app/helpers/user_forms_helper.rb
module UserFormsHelper
end

HTML/lesson 28 upgrade to data-base/UPGRADE/app/views/contacts/index.html.erb
<html>
	<head>
		<title>Codifun</title>
		<link rel="stylesheet" type="text/css" href="css/style.css">
	</head>
	<body>
		<h1 style="color: #302d41">Codifun Inspire Me</h1>
		
		<p><i>Lorem Ipsum is a fish text often used in print and web design. 
		Lorem Ipsum has been the standard “fish” for Latin texts since 
		the beginning of the 16th century. At that time, a nameless printer 
		created a large collection of font sizes and shapes using Lorem 
		Ipsum to print samples. Lorem Ipsum not only successfully survived 
		without noticeable changes for five centuries, but also stepped 
		into electronic design. Its popularization in modern times was the 
		publication of Letraset sheets with Lorem Ipsum samples in the 60s 
		and, more recently, electronic layout programs such as Aldus PageMaker, 
		in the templates of which Lorem Ipsum was used.</i></p>
		
		
		<table style="width:100%">
		  <tr>
			<td valign="top">Меню</td>
			<td valign="top">Контакты</td>
		  </tr>
		  <tr>
			<td valign="top" style="text-align: left;width:200px">
				<ul id="nav-menu">
					<li class="nav-item"><a href="<%= root_path %>">Главная страница</a></li>
					<li class="nav-item"><a href="<%= facts_index_path %>">Интересные факты</a></li>
					<li class="nav-item"><a href="<%= contacts_index_path %>">Контакты</a></li>
					<li class="nav-item"><a href="<%= new_user_form_path %>">Форма с личными данными</a></li>
				</ul>
			</td>
			<td valign="top">
				<p>
					наши Контакты
				</p>
			</td>
		  </tr>
		</table>

		<q>Знания создают ваше будущее!</q>
	</body>
</html>

HTML/lesson 28 upgrade to data-base/UPGRADE/app/views/facts/index.html.erb
<html>
	<head>
		<title>Codifun</title>
		<link rel="stylesheet" type="text/css" href="css/style.css">
	</head>
	<body>
		<h1 style="color: #302d41">Codifun Inspire Me</h1>
		
		<p><i>Lorem Ipsum is a fish text often used in print and web design. 
		Lorem Ipsum has been the standard “fish” for Latin texts since 
		the beginning of the 16th century. At that time, a nameless printer 
		created a large collection of font sizes and shapes using Lorem 
		Ipsum to print samples. Lorem Ipsum not only successfully survived 
		without noticeable changes for five centuries, but also stepped 
		into electronic design. Its popularization in modern times was the 
		publication of Letraset sheets with Lorem Ipsum samples in the 60s 
		and, more recently, electronic layout programs such as Aldus PageMaker, 
		in the templates of which Lorem Ipsum was used.</i></p>
		
		
		<table style="width:100%">
		  <tr>
			<td valign="top">Меню</td>
			<td valign="top"></td>
		  </tr>
		  <tr>
			<td valign="top" style="text-align: left;width:200px">
				<ul id="nav-menu">
					<li class="nav-item"><a href="<%= root_path %>">Главная страница</a></li>
					<li class="nav-item"><a href="<%= facts_index_path %>">Интересные факты</a></li>
					<li class="nav-item"><a href="<%= contacts_index_path %>">Контакты</a></li>
					<li class="nav-item"><a href="<%= new_user_form_path %>">Форма с личными данными</a></li>
				</ul>
			</td>
			<td valign="top">
				<p>
                    <q>Знания создают ваше будущее!</q>
				</p>
			</td>
		  </tr>
		</table>

		
	</body>
</html>

HTML/lesson 28 upgrade to data-base/UPGRADE/app/views/home/index.html.erb
<html>
	<head>
		<title>Codifun</title>
		<link rel="stylesheet" type="text/css" href="css/style.css">
	</head>
	<body>
		<h1 style="color: #302d41">Codifun Inspire Me</h1>
		
		<p><i>Lorem Ipsum is a fish text often used in print and web design. 
		Lorem Ipsum has been the standard “fish” for Latin texts since 
		the beginning of the 16th century. At that time, a nameless printer 
		created a large collection of font sizes and shapes using Lorem 
		Ipsum to print samples. Lorem Ipsum not only successfully survived 
		without noticeable changes for five centuries, but also stepped 
		into electronic design. Its popularization in modern times was the 
		publication of Letraset sheets with Lorem Ipsum samples in the 60s 
		and, more recently, electronic layout programs such as Aldus PageMaker, 
		in the templates of which Lorem Ipsum was used.</i></p>
		
		
		<table style="width:100%">
		  <tr>
			<th valign="top">Меню</th>
			<td valign="top"></td>
			<td valign="top"></td>
			<td valign="top"></td>
		  </tr>
		  <tr>
			<td valign="center" style="text-align: left;width:200px">
				<ul id="nav-menu">
					<li class="nav-item"><a href="<%= root_path %>">Главная страница</a></li>
					<li class="nav-item"><a href="<%= facts_index_path %>">Интересные факты</a></li>
					<li class="nav-item"><a href="<%= contacts_index_path %>">Контакты</a></li>
					<li class="nav-item"><a href="<%= new_user_form_path %>">Форма с личными данными</a></li>
				</ul>
			</td>
			<td valign="top">
				<h2 class="cntr">
					Название статья
				</h2>
				<img src="<%= asset_path("articol-1.png") %>" style="width: 100%;"></img>
				<h6 style="color: #009688; text-align: center;">Автор: codifun</h6>
				<p style="color: #5f5f5f; text-align: center;"><span class="clr">"Lorem ipsum dolor sit amet, 
				consectetur adipiscing elit, </span>sed do eiusmod tempor incididunt ut labore et 
				dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco 
				laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in 
				repreten in repre velit esse cillum dolore eu fugiat nulla pariatur. Excepteur 
				sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit 
				anim id est laborum. "</p>
				<br>
				<audio controls autoplay muted style="width: 100%;">
					<source src="<%= asset_path("audio.mp3") %>" type="audio/mp3">
				</audio>
			</td>
			<td valign="top">
				<h2 class="cntr">
					Название статья 2
				</h2>
				<img src="<%= asset_path("articol-2.png") %>" style="width: 100%;"></img>
				<h6 style="color: #009688; text-align: center;">Автор: codifun</h6>
				<p style="color: #5f5f5f; text-align: center;">"Lorem ipsum dolor sit amet, 
				consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et 
				dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco 
				laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in 
				repreten in repre velit esse cillum dolore eu fugiat nulla pariatur. Excepteur 
				sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit 
				anim id est laborum. "</p>
				<br>				
			</td>
			<td valign="top">
				<h2 class="cntr">
					Название статья 3
				</h2>
				<img src="<%= asset_path("articol-3.png") %>" style="width: 100%;"></img>
				<h6 style="color: #009688; text-align: center;">Автор: codifun</h6>
				<p style="color: #5f5f5f; text-align: center;">"Lorem ipsum dolor sit amet, 
				consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et 
				dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco 
				laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in 
				repreten in repre velit esse cillum dolore eu fugiat nulla pariatur. Excepteur 
				sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit 
				anim id est laborum. "</p>
				<br>				
			</td>
		  </tr>
		</table>

		<q>Знания создают ваше будущее!</q>
	</body>
</html>

HTML/lesson 28 upgrade to data-base/UPGRADE/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UPGRADE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <nav class="navbar navbar-dark bg-primary">
      <a class="navbar-brand" href="<%= root_path %>">Codifun</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="<%= root_path %>">Главная страница <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_user_form_path %>">Новая Анкета</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= user_forms_path %>">Все записавшиеся</a>
          </li>
          
        </ul>
      </div>
    </nav>
</head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

HTML/lesson 28 upgrade to data-base/UPGRADE/app/views/user_forms/index.html.erb
<% @userforms.each do |user| %>
    <div class="border-text">
        <h1>Имя: <%= user[:name] %></h1>
        <small>Фамилия: <%= user[:surname] %></small><br>
        <a href="<%= user_form_path(user) %>"><button class="btn btn-info">Просмотр</button></a>
        <hr>
    </div>
<% end %>

HTML/lesson 28 upgrade to data-base/UPGRADE/app/views/user_forms/show.html.erb
<p>
Имя: <%= @userform.name %><br>
Фамилия: <%= @userform.surname %><br>
Дата рождения: <%= @userform.date %><br>
Страна происхождения: <%= @userform.country %><br>
Интресы: <b class="lang"><i><%= @userform.html %>
                            <%= @userform.javascript %>
                            <%= @userform.php %>
                            <%= @userform.css %></i></b><br>
Email: <%= @userform.email %><br>
Password: <%= @userform.password %><br>
Уведомления: <%= @userform.notification%><br>
Ваше мнение о Codifun: <%= @userform.review %><br>
</p>

<%= link_to 'Удалить', user_form_path(@userform), method: :delete, data: { confirm: 'Вы уверены?'}, :class => 'btn btn-danger' %>